### ISSUE TITLE
Rarity Weight

### ISSUE THREAD

**Issue by inapeace0** [alephao/nftool#2]
❤❤❤❤❤❤❤
**Hi, I was trying to generate arts with the exact weights, finally, I found this module and tried.
But I was a bit surprised because I didn't see the result that I wanted.**

# Layer Structure

```
    00-Background
        |- 1.blue.png
        |- 2.white.png
        |- 3.green.png
    01-Body
        |- 1-maroon.png
        |- 2-nut.png
        |- 3-standard.png
        |- 4-yellow.png
    02-Expressions
        |- 1-dot.png
        |- 2-std_lord.png
        |- 3-standard.png
```

# config.yaml

```yaml
name: 'My Collection #{id}'
description: An awesome collection
external_link: https://myexternallink.com
image: ipfs://myHash/{id}
traits:
- trait_type: Background
  variants:
  - value: blue
    weight: 1
  - value: white
    weight: 2
  - value: green
    weight: 3
  is_optional: false
  optional_weight: 1
- trait_type: Body
  variants:
  - value: maroon
    weight: 1
  - value: nut
    weight: 2
  - value: standard
    weight: 3
  - value: yellow
    weight: 4
  is_optional: false
  optional_weight: 1
- trait_type: Expressions
  variants:
  - value: dot
    weight: 1
  - value: std_lord
    weight: 2
  - value: standard
    weight: 3
  is_optional: false
  optional_weight: 1
path_map:
  Background/blue: ./layers/00-Background/1-blue.png
  Background/green: ./layers/00-Background/3-green.png
  Background/white: ./layers/00-Background/2-white.png
  Body/maroon: ./layers/01-Body/1-maroon.png
  Body/nut: ./layers/01-Body/2-nut.png
  Body/standard: ./layers/01-Body/3-standard.png
  Body/yellow: ./layers/01-Body/4-yellow.png
  Expressions/dot: ./layers/02-Expressions/1-dot.png
  Expressions/standard: ./layers/02-Expressions/3-standard.png
  Expressions/std_lord: ./layers/02-Expressions/2-std_lord.png
```

# traits_rarity.json

```json
  {
    "total": 30,
    "traits": {
      "Background": {
        "blue": { "Total": 9, "Percentage": 0.3 },  //  Origin: 5               
        "green": { "Total": 10, "Percentage": 0.3333333333333333 }, // Origin: 10
        "white": { "Total": 11, "Percentage": 0.36666666666666664 } // Origin: 15
      },
      "Body": {
        "maroon": { "Total": 4, "Percentage": 0.13333333333333333 },  //  Origin: 3
        "nut": { "Total": 9, "Percentage": 0.3 }, //  Origin: 6
        "standard": { "Total": 8, "Percentage": 0.26666666666666666 },  //  Origin: 9
        "yellow": { "Total": 9, "Percentage": 0.3 } //  Origin: 12
      },
      "Expressions": {
        "dot": { "Total": 10, "Percentage": 0.3333333333333333 }, //  Origin: 5
        "standard": { "Total": 11, "Percentage": 0.36666666666666664 }, //  Origin: 10  
        "std_lord": { "Total": 9, "Percentage": 0.3 } //  Origin: 15
      }
    }
  }
```

🙋‍♂️ Please let me know what I made a mistake, and how I can solve this problem perfectly.

🙏 Thanks.

**Comment by alephao** [comment]
Hello @CaCaBlocker you made nothing wrong! The weight doesn't guarantee 100% precision, but I see you got some weird results, especially on "Body", so I'll have a look on that. 

In the meanwhile, try playing with other weights. For example, since you want a `5, 10, 15` distribution on `Background`, try using those numbers as weights, like in the example below:

```yaml
traits:
- trait_type: Background
  variants:
  - value: blue
    weight: 5
  - value: white
    weight: 10
  - value: green
    weight: 15
  is_optional: false
```

I'll have a better look into this later today
